/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import exceptions.CampoVazio;
import exceptions.DataInvalida;
import exceptions.DestinoInvalido;
import exceptions.EmailInvalido;
import exceptions.QuantidadeInvalida;
import exceptions.SexoInvalido;
import exceptions.TransporteInvalido;
import exceptions.ValorInvalido;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JPanel;
import passagem.Passagem;
import pessoas.Cliente;
import java.util.Date;
import javax.swing.JOptionPane;
import java.util.LinkedList;
import java.text.SimpleDateFormat;
import java.io.File;
import java.io.FileWriter;
import java.time.LocalDateTime;
import java.io.IOException;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import java.net.URL;

/**
 *
 * @author Júnior
 */
public class MainFrame extends javax.swing.JFrame {
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        ImageIcon icon = new ImageIcon("src/assets/icons/favicon-32x32.png");
        setIconImage(icon.getImage());
        
        telaCadastrados = new ClienteFrame();
        cadNovoUser = new NovoUsuario();
        initComponents();
        VendaPanel.setVisible(false);
        cadNovoUser.setVisible(false);
        LocalDateTime sessao = LocalDateTime.now();
        DateTimeFormatter formatador = DateTimeFormatter.ofPattern("dd-MM-yyyy-HHmmss");
        String sessaoformatada = sessao.format(formatador);
        arquivo = sessaoformatada;
        destinoComboBox.addItem("Rio Branco");
        destinoComboBox.addItem("Maceió");
        destinoComboBox.addItem("Macapá");
        destinoComboBox.addItem("Manaus");
        destinoComboBox.addItem("Salvador");
        destinoComboBox.addItem("Fortaleza");
        destinoComboBox.addItem("Brasília");
        destinoComboBox.addItem("Vitória");
        destinoComboBox.addItem("Goiânia");
        destinoComboBox.addItem("Cuiabá");
        destinoComboBox.addItem("Campo Grande");
        destinoComboBox.addItem("Belo Horizonte");
        destinoComboBox.addItem("Belém");
        destinoComboBox.addItem("João Pessoa");
        destinoComboBox.addItem("Curitiba");
        destinoComboBox.addItem("Recife");
        destinoComboBox.addItem("Teresina");
        destinoComboBox.addItem("Rio de Janeiro");
        destinoComboBox.addItem("Natal");
        destinoComboBox.addItem("Porto Alegre");
        destinoComboBox.addItem("Porto Velho");
        destinoComboBox.addItem("Boa Vista");
        destinoComboBox.addItem("Florianópolis");
        destinoComboBox.addItem("São Paulo");
        destinoComboBox.addItem("Aracaju");
        destinoComboBox.addItem("Palmas");
    }
    
    public ClienteFrame getTelaCadastrados() {
            return telaCadastrados;
	}

    public void setTelaCadastrados(ClienteFrame telaCadastrados) {
            this.telaCadastrados = telaCadastrados;
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        ClientesCadastradosFrame = new javax.swing.JFrame();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        VendaPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        sobrenomeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        paisBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        diaComboBox = new javax.swing.JComboBox<>();
        mesComboBox = new javax.swing.JComboBox<>();
        anoComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        sexoBox1 = new javax.swing.JRadioButton();
        sexoBox2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jComboBox5 = new javax.swing.JComboBox<>();
        destinoComboBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        aviaoButton = new javax.swing.JRadioButton();
        onibusButton = new javax.swing.JRadioButton();
        qtdComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        CPFField = new javax.swing.JFormattedTextField();
        RGField = new javax.swing.JFormattedTextField();
        valorField = new javax.swing.JFormattedTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        telefoneField = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        desembarqueField = new javax.swing.JFormattedTextField();
        embarqueField = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        CadastroLabel = new javax.swing.JLabel();
        ClientesButton = new javax.swing.JButton();
        GerarRelatorioButton = new javax.swing.JButton();
        VendaButton = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        NovoUserButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        SairButton = new javax.swing.JButton();
        RelatorioLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        SobreButton = new javax.swing.JButton();
        AjudaButton = new javax.swing.JButton();

        jLabel15.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel15.setText("Clientes cadastrados: ");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout ClientesCadastradosFrameLayout = new javax.swing.GroupLayout(ClientesCadastradosFrame.getContentPane());
        ClientesCadastradosFrame.getContentPane().setLayout(ClientesCadastradosFrameLayout);
        ClientesCadastradosFrameLayout.setHorizontalGroup(
            ClientesCadastradosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesCadastradosFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(ClientesCadastradosFrameLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel15)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        ClientesCadastradosFrameLayout.setVerticalGroup(
            ClientesCadastradosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesCadastradosFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );

        setTitle("RedLines");
        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(675, 540));
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        VendaPanel.setBackground(new java.awt.Color(51, 51, 51));
        VendaPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        VendaPanel.setToolTipText("");
        VendaPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        VendaPanel.setName("Vendas"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cliente");

        jLabel2.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("S:obrenome:");

        jLabel4.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CPF:");

        jLabel5.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RG:");

        jLabel6.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("País:");

        paisBox.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        paisBox.setForeground(new java.awt.Color(255, 255, 255));
        paisBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brasil" }));
        paisBox.setName(""); // NOI18N
        paisBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisBoxActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Data de Nascimento:");

        diaComboBox.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        diaComboBox.setForeground(new java.awt.Color(255, 255, 255));
        diaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mesComboBox.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        mesComboBox.setForeground(new java.awt.Color(255, 255, 255));
        mesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        mesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesComboBoxActionPerformed(evt);
            }
        });

        anoComboBox.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        anoComboBox.setForeground(new java.awt.Color(255, 255, 255));
        anoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano", "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));

        jLabel8.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sexo: ");

        buttonGroup1.add(sexoBox1);
        sexoBox1.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        sexoBox1.setForeground(new java.awt.Color(255, 255, 255));
        sexoBox1.setText("Masculino");
        sexoBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoBox1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(sexoBox2);
        sexoBox2.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        sexoBox2.setForeground(new java.awt.Color(255, 255, 255));
        sexoBox2.setText("Feminino");
        sexoBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoBox2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Telefone: ");

        jLabel10.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("E-mail: ");

        jLabel11.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Transporte");

        jLabel12.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Rota e horário");

        jComboBox5.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "São Luís" }));
        jComboBox5.setEnabled(false);

        destinoComboBox.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        destinoComboBox.setForeground(new java.awt.Color(255, 255, 255));
        destinoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Destino" }));

        jLabel13.setText("Vendas");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        buttonGroup2.add(aviaoButton);
        aviaoButton.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        aviaoButton.setForeground(new java.awt.Color(255, 255, 255));
        aviaoButton.setText("Avião");
        aviaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aviaoButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(onibusButton);
        onibusButton.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        onibusButton.setForeground(new java.awt.Color(255, 255, 255));
        onibusButton.setText("Ônibus");

        qtdComboBox.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        qtdComboBox.setForeground(new java.awt.Color(255, 255, 255));
        qtdComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quantidade", "1", "2", "3", "4", "5" }));
        qtdComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdComboBoxActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Valor (R$):");

        try {
            CPFField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CPFField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPFFieldActionPerformed(evt);
            }
        });

        try {
            RGField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        valorField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        valorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorFieldActionPerformed(evt);
            }
        });

        jToggleButton2.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jToggleButton2.setForeground(new java.awt.Color(204, 0, 51));
        jToggleButton2.setText("Cadastrar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        try {
            telefoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 51));
        jButton1.setText("Finalizar");
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        desembarqueField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("hh:mm"))));

        embarqueField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("hh:mm"))));

        jLabel18.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Embarque (HH:MM)");

        jLabel19.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Desembarque (HH:MM)");

        javax.swing.GroupLayout VendaPanelLayout = new javax.swing.GroupLayout(VendaPanel);
        VendaPanel.setLayout(VendaPanelLayout);
        VendaPanelLayout.setHorizontalGroup(
            VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VendaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(VendaPanelLayout.createSequentialGroup()
                        .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                            .addGroup(VendaPanelLayout.createSequentialGroup()
                                .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator1)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(VendaPanelLayout.createSequentialGroup()
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(VendaPanelLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(onibusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(aviaoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(qtdComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(VendaPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(valorField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(VendaPanelLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(destinoComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(desembarqueField, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                            .addComponent(embarqueField))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19)))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VendaPanelLayout.createSequentialGroup()
                        .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VendaPanelLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(VendaPanelLayout.createSequentialGroup()
                                        .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(5, 5, 5)
                                        .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nomeField, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                            .addComponent(CPFField))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(VendaPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sobrenomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(VendaPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(3, 3, 3)
                                                .addComponent(RGField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(paisBox, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(VendaPanelLayout.createSequentialGroup()
                                        .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VendaPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sexoBox1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sexoBox2))
                                            .addGroup(VendaPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(telefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VendaPanelLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(diaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        VendaPanelLayout.setVerticalGroup(
            VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VendaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(VendaPanelLayout.createSequentialGroup()
                        .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(sobrenomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(paisBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CPFField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RGField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(diaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(VendaPanelLayout.createSequentialGroup()
                                .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(sexoBox1)
                                    .addComponent(sexoBox2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11))
                .addGap(9, 9, 9)
                .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(VendaPanelLayout.createSequentialGroup()
                        .addComponent(aviaoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(onibusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(qtdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VendaPanelLayout.createSequentialGroup()
                        .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(embarqueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(destinoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desembarqueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(valorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton2))))
                .addGap(14, 14, 14)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(VendaPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        getContentPane().add(VendaPanel);

        MainPanel.setFocusable(false);
        MainPanel.setOpaque(false);
        MainPanel.setPreferredSize(new java.awt.Dimension(675, 540));

        CadastroLabel.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        CadastroLabel.setForeground(new java.awt.Color(255, 255, 255));
        CadastroLabel.setText("Cadastrar:");

        ClientesButton.setBackground(new java.awt.Color(51, 51, 51));
        ClientesButton.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        ClientesButton.setForeground(new java.awt.Color(255, 255, 255));
        ClientesButton.setText("Clientes");
        ClientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesButtonActionPerformed(evt);
            }
        });

        GerarRelatorioButton.setBackground(new java.awt.Color(51, 51, 51));
        GerarRelatorioButton.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        GerarRelatorioButton.setForeground(new java.awt.Color(255, 255, 255));
        GerarRelatorioButton.setText("Gerar relatório");
        GerarRelatorioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GerarRelatorioButtonMouseClicked(evt);
            }
        });
        GerarRelatorioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerarRelatorioButtonActionPerformed(evt);
            }
        });

        VendaButton.setBackground(new java.awt.Color(51, 51, 51));
        VendaButton.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        VendaButton.setForeground(new java.awt.Color(255, 255, 255));
        VendaButton.setText("Vendas");
        VendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendaButtonActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background.jpg"))); // NOI18N
        jLabel16.setName(""); // NOI18N
        jLabel16.setPreferredSize(new java.awt.Dimension(452, 378));

        NovoUserButton.setBackground(new java.awt.Color(51, 51, 51));
        NovoUserButton.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        NovoUserButton.setForeground(new java.awt.Color(255, 255, 255));
        NovoUserButton.setText("Novo usuário");
        NovoUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoUserButtonActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("@Redlines Tech. 2023");

        jPanel3.setOpaque(false);

        SairButton.setBackground(new java.awt.Color(51, 51, 51));
        SairButton.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        SairButton.setForeground(new java.awt.Color(204, 0, 51));
        SairButton.setText("Sair");
        SairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(SairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(SairButton)
                .addContainerGap())
        );

        RelatorioLabel.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        RelatorioLabel.setForeground(new java.awt.Color(51, 255, 51));
        RelatorioLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                RelatorioLabelFocusLost(evt);
            }
        });

        SobreButton.setBackground(new java.awt.Color(51, 51, 51));
        SobreButton.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        SobreButton.setForeground(new java.awt.Color(255, 255, 255));
        SobreButton.setText("Sobre");
        SobreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreButtonActionPerformed(evt);
            }
        });

        AjudaButton.setBackground(new java.awt.Color(51, 51, 51));
        AjudaButton.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        AjudaButton.setForeground(new java.awt.Color(255, 255, 255));
        AjudaButton.setText("Ajuda");
        AjudaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AjudaButtonMouseClicked(evt);
            }
        });
        AjudaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjudaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(CadastroLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AjudaButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SobreButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GerarRelatorioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ClientesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(VendaButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NovoUserButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RelatorioLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 679, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(CadastroLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VendaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NovoUserButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GerarRelatorioButton)
                    .addComponent(RelatorioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClientesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AjudaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SobreButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 544, Short.MAX_VALUE))
        );

        jLabel16.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(MainPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    private void ClientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesButtonActionPerformed
        telaCadastrados.setVisible(true);
    }//GEN-LAST:event_ClientesButtonActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
    try {
        	if(nomeField.getText().isEmpty()==true || sobrenomeField.getText().isEmpty()==true
        	   ||CPFField.getText().equalsIgnoreCase("   .   .   -  ")==true || RGField.getText().equalsIgnoreCase("  .   .   - ")==true 
        	   || telefoneField.getText().equalsIgnoreCase("(  )     -    ") || valorField.getText().isEmpty()==true || embarqueField.getText().isEmpty()==true || desembarqueField.getText().isEmpty()==true) {
        		String campo=null;
        		if(nomeField.getText().isEmpty()==true)
        			campo="nome";
        		if(sobrenomeField.getText().isEmpty()==true)
        			campo="sobrenome";
        		if(CPFField.getText().equalsIgnoreCase("   .   .   -  ")==true)
        			campo="CPF";
        		if(RGField.getText().equalsIgnoreCase("  .   .   - ")==true)
        			campo="RG";
        		if(telefoneField.getText().equalsIgnoreCase("(  )     -    "))
        			campo="telefone";
        		if(valorField.getText().isEmpty()==true)
        			campo="valor";
                        if(embarqueField.getText().isEmpty()==true)
                                campo="embarque";
                        if(desembarqueField.getText().isEmpty()==true)
                                campo="desembarque";
        		throw new CampoVazio(campo);
        }    
        Cliente c= new Cliente(CPFField.getText(),nomeField.getText()+" "+sobrenomeField.getText());
        if(emailField.getText().contains("@")==false || emailField.getText().contains(".")==false)
            	throw new EmailInvalido(emailField.getText());
            c.setEmail(emailField.getText());
            c.setPaís((String) paisBox.getSelectedItem());
            c.setRG(RGField.getText());
            c.setTelefone(telefoneField.getText());
   
        if(sexoBox1.isSelected())
            c.setSexo("Masculino");
        if(sexoBox2.isSelected())
            c.setSexo("Feminino");
        if(sexoBox1.isSelected()==false && sexoBox2.isSelected()==false)
            	throw new SexoInvalido();

        Date data= new Date();
        
        if(diaComboBox.getSelectedIndex()==0 || mesComboBox.getSelectedIndex()==0 || anoComboBox.getSelectedIndex()==0)
            	throw new DataInvalida(diaComboBox.getSelectedIndex(), mesComboBox.getSelectedIndex(),anoComboBox.getSelectedIndex());
        
        data.setDate((int) diaComboBox.getSelectedIndex());
        data.setMonth(mesComboBox.getSelectedIndex());
        data.setYear(Integer.parseInt((String) anoComboBox.getSelectedItem()));
        c.setDataNascimento(data);
        
        Date dataAtual= new Date();
            SimpleDateFormat formatoAno = new SimpleDateFormat("yyyy");
	        int anoAtual = Integer.parseInt(formatoAno.format(dataAtual));

        if(anoAtual-c.getDataNascimento().getYear()<18) {
        	throw new DataInvalida(diaComboBox.getSelectedIndex(), mesComboBox.getSelectedIndex(),anoComboBox.getSelectedIndex(),true);
            
        }

        Passagem p = new Passagem();
        p.setCliente(c);
        if(destinoComboBox.getSelectedIndex()==0)
            	throw new DestinoInvalido();
        p.setDestino((String) destinoComboBox.getSelectedItem());
            if(qtdComboBox.getSelectedIndex()==0)
            	throw new QuantidadeInvalida();        
        p.setQuantidade(qtdComboBox.getSelectedIndex());
        p.setValor(Double.parseDouble(valorField.getText()));
        if(p.getValor()<=0)
            	throw new ValorInvalido(p.getValor());
        
        p.setEmbarque(embarqueField.getText());
        p.setDesembarque(desembarqueField.getText());
        
        String transporte=null;

        if(aviaoButton.isSelected())
            transporte="Avião";
        if(onibusButton.isSelected())
            transporte="Ônibus";
        if(aviaoButton.isSelected()==false && onibusButton.isSelected()==false)
            	throw new TransporteInvalido();

        p.setTransporte(transporte);

        telaCadastrados.cadastrar(c.toString());
        listaPassagem.add(p);
        jTextArea1.setText(jTextArea1.getText()+ " ID: "  + p.getPassId() + " | Tipo: " + p.getTransporte() + " | Cliente: "  + c.getCpf() +   
                            " | Rota: "  + p.getOrigem() + "-" + p.getDestino() +   " | Quantidade: "  + p.getQuantidade() +   
                            " | VALOR(R$): "   + p.getValor() + "\n"
                                    + "EMBARCA ÀS: " + p.getEmbarque() + " AM | CHEGA ÀS: " + p.getDesembarque() + " PM\n");

        int confirmacao=JOptionPane.showConfirmDialog(null,"Os dados usados para o cadastros são esses?");
        if(confirmacao==0) {
            JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso!","Gui Swing",JOptionPane.PLAIN_MESSAGE);
            nomeField.setText("");
            sobrenomeField.setText("");
            emailField.setText("");
            diaComboBox.setSelectedIndex(0);
            mesComboBox.setSelectedIndex(0);
            anoComboBox.setSelectedIndex(0);
            telefoneField.setText("");
            RGField.setText("");
            CPFField.setText("");
        }
        nomeField.requestFocus();
        
        }catch(CampoVazio c) {
        	 JOptionPane.showMessageDialog(null,c.toString(),"Gui Swing",JOptionPane.PLAIN_MESSAGE);
        }catch(EmailInvalido e) {
        	 JOptionPane.showMessageDialog(null,e.toString(),"Gui Swing",JOptionPane.PLAIN_MESSAGE);
        }catch(SexoInvalido s) {
        	 JOptionPane.showMessageDialog(null,s.toString(),"Gui Swing",JOptionPane.PLAIN_MESSAGE);
        }catch(DataInvalida d) {
        	JOptionPane.showMessageDialog(null,d.toString(),"Gui Swing",JOptionPane.PLAIN_MESSAGE);
        }catch(QuantidadeInvalida q) {
        	JOptionPane.showMessageDialog(null,q.toString(),"Gui Swing",JOptionPane.PLAIN_MESSAGE);
        }catch(ValorInvalido v) {
        	JOptionPane.showMessageDialog(null,v.toString(),"Gui Swing",JOptionPane.PLAIN_MESSAGE);
        }catch(TransporteInvalido t) {
        	JOptionPane.showMessageDialog(null,t.toString(),"Gui Swing",JOptionPane.PLAIN_MESSAGE);
        }catch(DestinoInvalido Di) {
        	JOptionPane.showMessageDialog(null,Di.toString(),"Gui Swing",JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void CPFFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPFFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPFFieldActionPerformed

    private void qtdComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtdComboBoxActionPerformed

    private void aviaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aviaoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aviaoButtonActionPerformed

    private void sexoBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoBox2ActionPerformed

    private void sexoBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoBox1ActionPerformed

    private void mesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesComboBoxActionPerformed

    private void paisBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paisBoxActionPerformed

    private void VendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendaButtonActionPerformed
        VendaPanel.setVisible(true);
        VendaButton.setVisible(false);
    }//GEN-LAST:event_VendaButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VendaPanel.setVisible(false);
        VendaButton.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairButtonActionPerformed
        String[] opcoes = {"Sim", "Não"};
        int resposta = JOptionPane.showOptionDialog(
                null,
                "Deseja mesmo sair?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opcoes,
                opcoes[0]);

        if (resposta == JOptionPane.YES_OPTION) {
            System.out.println("Saindo.");
               this.setVisible(false);
               this.dispose();
               LoginFrame login = new LoginFrame();
               login.setVisible(true);
        } else {
            
        }
    }//GEN-LAST:event_SairButtonActionPerformed

    private void valorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorFieldActionPerformed

    private void NovoUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoUserButtonActionPerformed
       cadNovoUser.setVisible(true);
    }//GEN-LAST:event_NovoUserButtonActionPerformed

    private void GerarRelatorioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerarRelatorioButtonActionPerformed
        try {
          File Relatorio = new File("src/Relatorios/"+ arquivo + ".txt");
          FileWriter registrar = new FileWriter("src/Relatorios/"+ arquivo + ".txt");
          if (Relatorio.createNewFile()) {
            registrar.append("" + arquivo);
            registrar.append("\n"+jTextArea1.getText());
            registrar.append("\n-----------------------------------\n");
            registrar.close();
            System.out.println("Arquivo criado: " + Relatorio.getName());
            jTextArea1.setText("");
            RelatorioLabel.setText("Relatório gerado com sucesso!");
          } else {
            System.out.println("O arquivo já existe. Sobreescrevendo.");
            registrar.append("\n" + arquivo);
            registrar.append("\n"+jTextArea1.getText());
            registrar.append("\n-----------------------------------");
            registrar.close();
            jTextArea1.setText("");
            RelatorioLabel.setText("Relatório gerado com sucesso!");
          }
        } catch (IOException e) {
          System.out.println("Ocorreu um erro.");
          e.printStackTrace();
        }
    }//GEN-LAST:event_GerarRelatorioButtonActionPerformed

    private void GerarRelatorioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GerarRelatorioButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GerarRelatorioButtonMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        RelatorioLabel.setText("");
    }//GEN-LAST:event_formMouseClicked

    private void RelatorioLabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RelatorioLabelFocusLost
        RelatorioLabel.setText("");
    }//GEN-LAST:event_RelatorioLabelFocusLost

    private void SobreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreButtonActionPerformed
       ImageIcon imagem = new ImageIcon("src/assets/icons/android-chrome-192x192.png");
       String option = "De nada!";
        
        String mensagem = "<html><div style='text-align: center;'>"
                + "'RedLines' é um trabalho de<br>"
                + "Rudney Fonseca e José Júnior<br>"
                + "para a disciplina de Programação Orientada a Objetos<br>"
                + "Sistemas de Informação - 2º Período - IFMA-MTC.<br>"
                + "Obrigado!</div></html>";

         JOptionPane.showMessageDialog(
                null,
                mensagem,
                "RedLines agradece!",
                JOptionPane.INFORMATION_MESSAGE,
                imagem
        );
    }//GEN-LAST:event_SobreButtonActionPerformed

    private void AjudaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AjudaButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AjudaButtonMouseClicked

    private void AjudaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjudaButtonActionPerformed
        String mensagem =  "<html><div style='text-align: center;'>" +
                "Visite: <a href='https://github.com/jjuniorbrasil/Projeto-Final-POO'>https://github.com/jjuniorbrasil/Projeto-Final-POO</a><br>" +
                "ou envie um e-mail para<br>" +
                "rudney.fonseca@acad.ifma.edu.br<br>" +
                "junior.brasil@acad.ifma.edu.br</div></html>";

        JOptionPane.showMessageDialog(
                null,
                mensagem,
                "Ajuda",
                JOptionPane.INFORMATION_MESSAGE
        );     
    }//GEN-LAST:event_AjudaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }
    
    private String arquivo;
    private NovoUsuario cadNovoUser;
    private LinkedList<Passagem> listaPassagem = new LinkedList<>();
    private ClienteFrame telaCadastrados;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjudaButton;
    private javax.swing.JFormattedTextField CPFField;
    private javax.swing.JLabel CadastroLabel;
    private javax.swing.JButton ClientesButton;
    private javax.swing.JFrame ClientesCadastradosFrame;
    private javax.swing.JButton GerarRelatorioButton;
    private javax.swing.JPanel MainPanel;
    public javax.swing.JButton NovoUserButton;
    private javax.swing.JFormattedTextField RGField;
    private javax.swing.JLabel RelatorioLabel;
    private javax.swing.JButton SairButton;
    private javax.swing.JButton SobreButton;
    private javax.swing.JButton VendaButton;
    private javax.swing.JPanel VendaPanel;
    private javax.swing.JComboBox<String> anoComboBox;
    private javax.swing.JRadioButton aviaoButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JFormattedTextField desembarqueField;
    private javax.swing.JComboBox<String> destinoComboBox;
    private javax.swing.JComboBox<String> diaComboBox;
    private javax.swing.JTextField emailField;
    private javax.swing.JFormattedTextField embarqueField;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JComboBox<String> mesComboBox;
    private javax.swing.JTextField nomeField;
    private javax.swing.JRadioButton onibusButton;
    private javax.swing.JComboBox<String> paisBox;
    private javax.swing.JComboBox<String> qtdComboBox;
    private javax.swing.JRadioButton sexoBox1;
    private javax.swing.JRadioButton sexoBox2;
    private javax.swing.JTextField sobrenomeField;
    private javax.swing.JFormattedTextField telefoneField;
    private javax.swing.JFormattedTextField valorField;
    // End of variables declaration//GEN-END:variables
}
